/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
  @Test
  public void appHasAGreeting() {
    App classUnderTest = new App();
    assertNotNull("app should have a greeting", classUnderTest.getGreeting());
  }

  @Test
  public void testAppReternHelloWorld() {
    App classUnderTest = new App();
    assertEquals("Hello World!", classUnderTest.getGreeting());
  }

  @Test
  public void testSum() {
    Calculate calculate = new Calculate();
    int expected = 5;
    assertEquals(expected, calculate.sum(2, 3));
  }

  @Test
  public void testAve1() {
    Calculate calculate = new Calculate();
    double expected = 2.5;
    assertEquals(expected, calculate.ave1(2, 3), 0.01);
  }

  @Test
  public void allSum() {
    Calculate calculate = new Calculate();
    int expected = 55;
    assertEquals(expected, calculate.allSum(1, 10), 0.01);
  }

  @Test
  public void testAve2() {
    Calculate calculate = new Calculate();
    double expected = 5.5;
    assertEquals(expected, calculate.ave2(1, 10), 0.01);
  }

  @Test
  public void oddSum() {
    Calculate calculate = new Calculate();
    int expected = 25;
    assertEquals(expected, calculate.oddSum(1, 10), 0.01);
  }

  @Test
  public void evenSum() {
    Calculate calculate = new Calculate();
    int expected = 30;
    assertEquals(expected, calculate.evenSum(1, 10), 0.01);
  }

}
